### ISSUE TITLE
JUnit Test EverSdk problem

### ISSUE THREAD

**Issue by winfredSui2016** [deplant/java4ever-framework#21]
hi, i met problem when try to builder the EverSdk in https://github.com/deplant/java4ever-framework, what should i do when i run the test case?

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: unresolved symbol: tc_create_context
	at tech.deplant.java4ever.binding.ffi.ton_client.lambda$findOrThrow$0(ton_client.java:33)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at tech.deplant.java4ever.binding.ffi.ton_client.findOrThrow(ton_client.java:33)
	at tech.deplant.java4ever.binding.ffi.ton_client$tc_create_context.<clinit>(ton_client.java:328)
	at tech.deplant.java4ever.binding.ffi.ton_client.tc_create_context(ton_client.java:369)
	at tech.deplant.java4ever.binding.ffi.NativeMethods.tcCreateContext(NativeMethods.java:11)
	at tech.deplant.java4ever.binding.EverSdk.createWithConfig(EverSdk.java:211)
	at tech.deplant.java4ever.binding.EverSdk$Builder.build(EverSdk.java:756)
```

my test code is below:
```
        int offlineContext = EverSdk.builder()
                .networkSignatureId(1L)
                .networkQueryTimeout(300_000L)
                .build();
        var template = new EverWalletTemplate();

        var seed = Seed.ofRandom(offlineContext);// creates new seed
        var keys = seed.deriveCredentials(offlineContext); // derives keys from seed
        // let's calculate future EVER Wallet address
        var stateInit = template.getStateInit(offlineContext, keys.publicKey(), BigInteger.ZERO);
        var address = template.getAddress(offlineContext, 0, stateInit);
        // let's create message bodies offline
        // here we send sendTransaction to ourselves
        var body = new EverWalletContract(offlineContext, address, keys).sendTransaction(address, BigInteger.ONE, false)
                .toPayload(false);

        System.out.printf("Address: %s%n", address);
        System.out.printf("Seed: %s, public: %s%n", seed.phrase(), keys.publicKey());
        System.out.printf("Message body: %s%n", body);
        System.out.printf("State Init: %s%n", stateInit);

        int onlineContext = EverSdk.createWithEndpoint("https://gql.venom.foundation/graphql");
        // let's send messages when we're online
        EverSdk.sendExternalMessage(onlineContext,
                address.makeAddrStd(),
                EverWalletTemplate.DEFAULT_ABI().ABI(),
                stateInit.cellBoc(),
                body.cellBoc(),
                null);
```

**Comment by winfredSui2016** [comment]
sorry,I forgot to add the loading process, it's ok now
`EverSdk.load();`
